name: example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  signals:
    path: ../../signals

dev_dependencies:
  custom_lint: ^0.7.0
  signals_lint:
    path: ../
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
