name: signals_flutter
description: The signals library exposes four core functions which are the building blocks to model any business logic you can think of.
version: 5.0.0-beta.15
repository: https://github.com/rodydavis/signals.dart
homepage: https://dartsignals.dev/
documentation: https://dartsignals.dev/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  signals_core: ^5.0.0-beta.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

topics:
  - signal
  - reactive
  - state
  - signals
  - rx

scripts:
  coverage:
    - flutter test --coverage
    - genhtml coverage/lcov.info -o coverage/html
    - open coverage/html/index.html
