name: rxdart_example
description: RxDart + signals
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.18.0
  rxdart: ^0.28.0
  signals: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  lints: ^5.0.0

resolution: workspace
