name: example
description: Example signals project
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  signals_flutter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
