name: crud_dio
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  signals: ^6.0.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  copy_with_extension: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^6.0.1
  retrofit_generator: '>=8.1.0'

flutter:
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch

resolution: workspace
