name: signals_hooks
description: "flutter_hooks bindings for signals"
version: 0.1.1
repository: https://github.com/rodydavis/signals.dart
homepage: https://dartsignals.dev/
documentation: https://dartsignals.dev/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  signals_flutter: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
