name: signals_hooks
description: "flutter_hooks bindings for signals"
version: 0.4.0
repository: https://github.com/rodydavis/signals.dart
homepage: https://dartsignals.dev/
documentation: https://dartsignals.dev/

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.18.0 <1.0.0"
  signals: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
