name: signals_lint
description: linter and developer tool for signals
version: 6.0.0
repository: https://github.com/rodydavis/signals.dart
homepage: https://dartsignals.dev/
documentation: https://dartsignals.dev/
topics:
  - state-management
  - state
  - signals
  - rx
  - linter

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  analyzer: ">=7.0.0 <9.0.0"
  analyzer_plugin: ">=0.11.0 <0.14.0"
  collection: ^1.17.2
  custom_lint_builder: ^0.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.9
  signals: ^6.0.2
