name: signals_dart_examples
description: Pure dart examples using signals
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.18.0
  signals: ^6.0.0
  sqlite_async: ^0.6.1
  test: ^1.25.2

dev_dependencies:
  lints: ^5.0.0

resolution: workspace
