name: signals_core
description: The signals library exposes four core functions which are the building blocks to model any business logic you can think of.
version: 6.0.0
repository: https://github.com/rodydavis/signals.dart
homepage: https://dartsignals.dev/
documentation: https://dartsignals.dev/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  preact_signals: ^1.8.3

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.24.0

topics:
  - signal
  - reactive
  - state
  - signals
  - rx

scripts:
  coverage:
    - dart pub global run coverage:test_with_coverage
    - genhtml coverage/lcov.info -o coverage/html
    - open coverage/html/index.html