name: eval_calculator
description: Calculator that is driven by dynamic signals at runtime
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  signals: ^6.0.0
  analyzer: '>=6.4.1'
  cupertino_icons: ^1.0.8
  material_table_view: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

resolution: workspace
