name: preact_signals
description: Dart port of Preact.js Signals
version: 1.9.3
repository: https://github.com/rodydavis/signals.dart
homepage: https://dartsignals.dev/
documentation: https://dartsignals.dev/

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.8
