name: preact_signals
description: Dart port of Preact.js Signals
version: 1.8.1
repository: https://github.com/rodydavis/signals.dart
homepage: https://dartsignals.dev/
documentation: https://dartsignals.dev/

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.25.8
