name: drift_example
description: SQLite via drift and signals
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.9.0
  go_router: ^13.2.4
  signals: ^5.5.0
  flutter_colorpicker: ^1.0.3
  file_picker: ^8.0.0+1
  sqlite3: ^2.4.2
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.2
  drift_dev: ^2.16.0
  build_runner: ^2.4.9
  build: ^2.4.1
  build_web_compilers: ^4.0.10

flutter:
  uses-material-design: true
