name: html_canvas
description: Signals and the canvas
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.3.0

dependencies:
  web: ^0.5.1
  signals:
    path: ../../packages/signals

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  lints: ^3.0.0

scripts:
  dev: webdev serve
