name: signals_devtools_extension
description: Signals DevTools extension.
publish_to: "none"
version: 1.1.0
environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  devtools_extensions: ^0.4.0
  devtools_app_shared: ^0.4.0
  faker: ^2.1.0
  signals:
    path: ../signals
  graphview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

scripts:
  dev: flutter run -d chrome --dart-define=use_simulated_environment=true
  build:
    - flutter pub get
    - dart run devtools_extensions build_and_copy \
      --source=. \
      --dest=../signals/extension/devtools 