name: signals
description: "Reactivity made simple. Do more by doing less. Supports Flutter and any Dart project including HTML/JS, CLI, Shelf Server, VM and more."
repository: https://github.com/rodydavis/signals.dart
homepage: https://rodydavis.github.io/signals.dart
documentation: https://rodydavis.github.io/signals.dart
version: 1.5.10

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

topics:
  - signal
  - reactive
  - state
  - signals
  - rx

screenshots:
  - description: "DevTools signals graph view"
    path: doc/screenshots/graph.png
  - description: "DevTools signals list view"
    path: doc/screenshots/list.png

scripts:
  coverage:
    - flutter test --coverage
    - genhtml coverage/lcov.info -o coverage/html
